pipeline:
  cargo_fmt:
    image: rustdocker/rust:nightly
    commands:
      - /root/.cargo/bin/cargo fmt -- --check

  cargo_check:
    image: rust:1.70-bullseye
    environment:
      CARGO_HOME: .cargo
    commands:
      - cargo check --all-features --all-targets

  cargo_clippy:
    image: rust:1.70-bullseye
    environment:
      CARGO_HOME: .cargo
    commands:
      - rustup component add clippy
      - cargo clippy --all-targets --all-features --
        -D warnings -D deprecated -D clippy::perf -D clippy::complexity
        -D clippy::dbg_macro -D clippy::inefficient_to_string
        -D clippy::items-after-statements -D clippy::implicit_clone
        -D clippy::wildcard_imports -D clippy::cast_lossless
        -D clippy::manual_string_new -D clippy::redundant_closure_for_method_calls
      - cargo clippy --all-features -- -D clippy::unwrap_used

  cargo_test:
    image: rust:1.70-bullseye
    environment:
      CARGO_HOME: .cargo
    commands:
      - cargo test --all-features --no-fail-fast

  cargo_doc:
    image: rust:1.70-bullseye
    environment:
      CARGO_HOME: .cargo
    commands:
      - cargo doc --all-features

  cargo_run_actix_example:
    image: rust:1.70-bullseye
    environment:
      CARGO_HOME: .cargo
    commands:
      - cargo run --example local_federation actix-web

  cargo_run_axum_example:
    image: rust:1.70-bullseye
    environment:
      CARGO_HOME: .cargo
    commands:
      - cargo run --example local_federation axum
