variables:
  - &rust_image "rust:1.77-bullseye"
  
steps:
  cargo_fmt:
    image: rustdocker/rust:nightly
    commands:
      - /root/.cargo/bin/cargo fmt -- --check
    when:
      - event: pull_request

  cargo_check:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo
    commands:
      - cargo check --all-features --all-targets
    when:
      - event: pull_request

  cargo_clippy:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo
    commands:
      - rustup component add clippy
      - cargo clippy --all-targets --all-features --
        -D warnings -D deprecated -D clippy::perf -D clippy::complexity
        -D clippy::dbg_macro -D clippy::inefficient_to_string
        -D clippy::items-after-statements -D clippy::implicit_clone
        -D clippy::wildcard_imports -D clippy::cast_lossless
        -D clippy::manual_string_new -D clippy::redundant_closure_for_method_calls
      - cargo clippy --all-features -- -D clippy::unwrap_used
    when:
      - event: pull_request

  cargo_test:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo
    commands:
      - cargo test --all-features --no-fail-fast
    when:
      - event: pull_request

  cargo_doc:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo
    commands:
      - cargo doc --all-features
    when:
      - event: pull_request

  cargo_run_actix_example:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo
    commands:
      - cargo run --example local_federation actix-web
    when:
      - event: pull_request

  cargo_run_axum_example:
    image: *rust_image
    environment:
      CARGO_HOME: .cargo
    commands:
      - cargo run --example local_federation axum
    when:
      - event: pull_request
